In [12]:
# SMU module Testing
import pyvisa
import time
from SMU_drivers.Keysight_SMU import SMU
from SMU_drivers.Keysight_B2902B import B2902B

In [14]:
rm = pyvisa.ResourceManager()
A_res = rm.open_resource('TCPIP0::192.168.0.101::inst0::INSTR')
A = B2902B(A_res, 'A')
A.set_standby_zero()
A.set_output_state('on')

s1 = A.SMU1
s2 = A.SMU2

In [15]:
A.clear()
A.set_data_format('voltage,current')
A.resource.query(f'sense1:data?;:sense2:data?')

'+1.000000E-06,+0.000000E+00,+9.938700E-02,+2.300000E-08,+1.993800E-01,+2.200000E-08,+2.993800E-01,+2.400000E-08,+3.993930E-01,+2.100000E-08,+4.993920E-01,+2.400000E-08,+5.993650E-01,+2.400000E-08,+6.993730E-01,+2.300000E-08,+7.993860E-01,+2.300000E-08,+8.993970E-01,+2.500000E-08,+9.993840E-01,+2.400000E-08,+1.000000E+00,+3.000000E-09,+9.006150E-01,-1.900000E-08,+8.006020E-01,-1.700000E-08,+7.006120E-01,-1.900000E-08,+6.006230E-01,-1.800000E-08,+5.006200E-01,-1.800000E-08,+4.006190E-01,-1.700000E-08,+3.006160E-01,-1.800000E-08,+2.006210E-01,-1.700000E-08,+1.006190E-01,-1.600000E-08,+6.140000E-04,-1.500000E-08;+1.000000E-06,-5.200000E-08,+9.937300E-02,-3.100000E-08,+1.993830E-01,-2.600000E-08,+2.993850E-01,-2.200000E-08,+3.993830E-01,-1.400000E-08,+4.993830E-01,-1.100000E-08,+5.993470E-01,-5.000000E-09,+6.993820E-01,-7.000000E-09,+7.993850E-01,-3.000000E-09,+8.993860E-01,+1.000000E-09,+9.993840E-01,-1.000000E-09,+9.999990E-01,-1.200000E-08,+9.006170E-01,-2.800000E-08,+8.006110E-01,-2.60

In [10]:
A.memory_reset()

'Instrument was reset.'

In [16]:
A.check_instument_connection()

True

In [12]:
A.resource.clear()

In [8]:

A.beep(1000, 1)

'A: Beep at the frequency 1000 Hz for 1 s'

In [17]:
A.get_errors()

['-113,"Undefined header"\n',
 '-410,"Query INTERRUPTED"\n',
 '-113,"Undefined header"\n',
 '-410,"Query INTERRUPTED"\n',
 '-113,"Undefined header"\n',
 '-410,"Query INTERRUPTED"\n',
 '-113,"Undefined header"\n',
 '-410,"Query INTERRUPTED"\n',
 '-113,"Undefined header"\n',
 '-410,"Query INTERRUPTED"\n',
 '-113,"Undefined header"\n',
 '-410,"Query INTERRUPTED"\n',
 '-113,"Undefined header"\n',
 '-410,"Query INTERRUPTED"\n',
 '-113,"Undefined header"\n',
 '-410,"Query INTERRUPTED"\n',
 '-113,"Undefined header"\n',
 '-410,"Query INTERRUPTED"\n',
 '-113,"Undefined header"\n',
 '-350,"Queue overflow"\n']

In [106]:
s1.resource.clear()

In [55]:
s1.get_trigger_config()

({'source': 'BUS',
  'count': '+22',
  'delay': '+0.00000000E+000',
  'output': False},
 {'source': 'BUS',
  'count': '+22',
  'delay': '+0.00000000E+000',
  'output': False})

In [133]:
A_res.clear()

In [136]:
A.get_errors()

In [9]:
A.clear()
s1.set_arm_BUS()
s1.set_trigger_BUS(22)
s2.set_arm_BUS()
s2.set_trigger_BUS(22)
# print(s1.get_trigger_config())
s1.set_sweep_voltage(1, 11)
s2.set_sweep_voltage(1, 11)
A.initiate()
A.arm()
for i in range(22):
    A.trigger()
    time.sleep(200e-3)
    print(A.SMU1.get_sense_data())
    print(A.SMU2.get_sense_data())
    # print(A.fetch_array('voltage'), A.fetch_array('current'))
# print(A.fetch_array('voltage'), A.fetch_array('current'))
# s1.resource.clear()

+0.000000E+00,+1.686700E-08

-2.470000E-04,+5.013040E-07

+0.000000E+00,+1.686700E-08,+1.000050E-01,+1.748500E-08

-2.470000E-04,+5.013040E-07,+1.001090E-01,+6.096480E-07

+0.000000E+00,+1.686700E-08,+1.000050E-01,+1.748500E-08,+1.999870E-01,-1.220500E-08

-2.470000E-04,+5.013040E-07,+1.001090E-01,+6.096480E-07,+1.996820E-01,-4.317430E-07

+0.000000E+00,+1.686700E-08,+1.000050E-01,+1.748500E-08,+1.999870E-01,-1.220500E-08,+3.000010E-01,+1.636000E-09

-2.470000E-04,+5.013040E-07,+1.001090E-01,+6.096480E-07,+1.996820E-01,-4.317430E-07,+3.001610E-01,+6.581900E-08

+0.000000E+00,+1.686700E-08,+1.000050E-01,+1.748500E-08,+1.999870E-01,-1.220500E-08,+3.000010E-01,+1.636000E-09,+3.999960E-01,+6.116000E-09

-2.470000E-04,+5.013040E-07,+1.001090E-01,+6.096480E-07,+1.996820E-01,-4.317430E-07,+3.001610E-01,+6.581900E-08,+3.999080E-01,+1.141730E-07

+0.000000E+00,+1.686700E-08,+1.000050E-01,+1.748500E-08,+1.999870E-01,-1.220500E-08,+3.000010E-01,+1.636000E-09,+3.999960E-01,+6.116000E-09,+5.000090E

In [9]:
import numpy as np
s = '+0.000000E+00,+1.686700E-08,+1.000050E-01,+1.748500E-08,+1.999870E-01,-1.220500E-08,+3.000010E-01,+1.636000E-09,+3.999960E-01,+6.116000E-09,+5.000090E-01,-1.177100E-08,+5.999990E-01,+1.749000E-08,+6.999900E-01,-2.115000E-09,+7.999950E-01,+1.283100E-08,+8.999960E-01,-1.521900E-08,+1.000003E+00,-1.458000E-09,+9.999980E-01,+8.766000E-09,+8.999940E-01,-1.418400E-08,+8.000100E-01,-1.216000E-09,+6.999940E-01,+1.126700E-08,+6.000040E-01,+2.758000E-09,+4.999890E-01,+1.430600E-08,+3.999830E-01,-5.057000E-09,+2.999970E-01,-8.850000E-09,+2.000040E-01,+1.047400E-08,+9.999800E-02,+1.231100E-08,-4.000000E-06,-1.593200E-08;-2.470000E-04,+5.013040E-07,+1.001090E-01,+6.096480E-07,+1.996820E-01,-4.317430E-07,+3.001610E-01,+6.581900E-08,+3.999080E-01,+1.141730E-07,+5.003280E-01,-2.405020E-07,+6.000490E-01,+6.205330E-07,+6.997390E-01,-1.413580E-07,+7.997110E-01,+2.299570E-07,+8.998130E-01,-5.388240E-07,+1.000192E+00,-1.619400E-08,+9.999390E-01,+1.887120E-07,+8.997980E-01,-5.082880E-07,+8.001960E-01,-1.058300E-08,+6.998760E-01,+2.161110E-07,+6.002400E-01,+1.204790E-07,+4.996870E-01,+3.280420E-07,+3.997370E-01,-1.887000E-07,+3.000260E-01,-1.784620E-07,+2.003240E-01,+3.832200E-07,+9.974300E-02,+2.556680E-07,-2.080000E-04,-5.859980E-07\n'
res1, res2 = s.split(';')
np.array(res1.split(','), dtype=float)

array([ 0.000000e+00,  1.686700e-08,  1.000050e-01,  1.748500e-08,
        1.999870e-01, -1.220500e-08,  3.000010e-01,  1.636000e-09,
        3.999960e-01,  6.116000e-09,  5.000090e-01, -1.177100e-08,
        5.999990e-01,  1.749000e-08,  6.999900e-01, -2.115000e-09,
        7.999950e-01,  1.283100e-08,  8.999960e-01, -1.521900e-08,
        1.000003e+00, -1.458000e-09,  9.999980e-01,  8.766000e-09,
        8.999940e-01, -1.418400e-08,  8.000100e-01, -1.216000e-09,
        6.999940e-01,  1.126700e-08,  6.000040e-01,  2.758000e-09,
        4.999890e-01,  1.430600e-08,  3.999830e-01, -5.057000e-09,
        2.999970e-01, -8.850000e-09,  2.000040e-01,  1.047400e-08,
        9.999800e-02,  1.231100e-08, -4.000000e-06, -1.593200e-08])

In [48]:
A.get_errors()

['-113,"Undefined header"\n', '-113,"Undefined header"\n']

In [31]:
A.SMU1.get_sense_data()

'+1.000000E-06,+2.000000E-09,+9.876900E-02,+2.800000E-08,+1.987560E-01,+3.700000E-08,+2.987480E-01,+4.500000E-08,+3.987740E-01,+5.500000E-08,+4.987760E-01,+6.400000E-08,+5.987440E-01,+7.400000E-08,+6.987400E-01,+8.200000E-08,+7.987550E-01,+8.900000E-08,+8.987830E-01,+1.010000E-07,+9.987670E-01,+1.130000E-07,+1.000001E+00,+9.400000E-08,+9.012310E-01,+6.100000E-08,+8.012150E-01,+5.200000E-08,+7.012420E-01,+4.000000E-08,+6.012590E-01,+3.400000E-08,+5.012510E-01,+2.400000E-08,+4.012260E-01,+1.700000E-08,+3.012260E-01,+1.100000E-08,+2.012550E-01,+0.000000E+00,+1.012460E-01,-1.300000E-08,+1.224000E-03,-2.600000E-08\n'

In [28]:
A.set_data_format('volt,curr')

'A: Data output format is set to volt,curr'

In [17]:
s1.resource.clear()
s1.set_arm_BUS()
s1.set_trigger_timer(0.1, 22)
s2.set_arm_BUS()
s2.set_trigger_timer(0.1, 22)
# print(s1.get_trigger_config())
s1.set_sweep_voltage(1, 11)
s2.set_sweep_voltage(1, 11)
A.set_data_format('voltage,current')
time.sleep(0.1)
A.initiate()
A.arm()
for i in range(22):
    print(A.SMU1.get_sense_data(True))
    time.sleep(0.1)
    # print(A.SMU2.get_sense_data(True))
    # print(A.SMU1.query('trace:data?'))
    # print(A.fetch_array('voltage'), A.fetch_array('current'))
# print(A.fetch_array('voltage'), A.fetch_array('current'))
# s1.resource.clear()
# A.fetch_array('voltage')
A.fetch_array('voltage')

+9.910000E+37,+9.910000E+37

+9.939100E-02,+2.200000E-08

+1.993860E-01,+2.800000E-08

+2.993800E-01,+4.200000E-08

+3.993900E-01,+5.400000E-08

+4.993920E-01,+5.900000E-08

+5.993790E-01,+7.000000E-08

+6.993740E-01,+8.000000E-08

+7.993800E-01,+9.000000E-08

+8.993980E-01,+9.800000E-08

+9.993880E-01,+1.090000E-07

+1.000001E+00,+9.300000E-08

+9.006130E-01,+7.600000E-08

+8.006020E-01,+6.100000E-08

+7.006190E-01,+5.300000E-08

+5.006200E-01,+3.600000E-08

+4.006070E-01,+2.700000E-08

+3.006100E-01,+1.600000E-08

+2.006190E-01,+4.000000E-09

+1.006170E-01,-3.000000E-09

+6.080000E-04,-1.500000E-08

+6.080000E-04,-1.500000E-08



(array([2.000000e-06, 9.939100e-02, 1.993860e-01, 2.993800e-01,
        3.993900e-01, 4.993920e-01, 5.993790e-01, 6.993740e-01,
        7.993800e-01, 8.993980e-01, 9.993880e-01, 1.000001e+00,
        9.006130e-01, 8.006020e-01, 7.006190e-01, 6.006250e-01,
        5.006200e-01, 4.006070e-01, 3.006100e-01, 2.006190e-01,
        1.006170e-01, 6.080000e-04]),
 array([0.00000e+00, 9.93870e-02, 1.99383e-01, 2.99390e-01, 3.99385e-01,
        4.99383e-01, 5.99348e-01, 6.99370e-01, 7.99385e-01, 8.99385e-01,
        9.99382e-01, 9.99998e-01, 9.00617e-01, 8.00627e-01, 7.00614e-01,
        6.00617e-01, 5.00651e-01, 4.00619e-01, 3.00617e-01, 2.00623e-01,
        1.00617e-01, 6.14000e-04]))

In [117]:
import pyvisa.constants


complete = pyvisa.constants.EventType.io_completion

A.resource.enable_event(complete, pyvisa.constants.VI_QUEUE)

In [15]:
A.fetch_array('current')

'ERROR: A:\n\tVISA ERROR:\n\tCommand: "fetch:array:current? (@1,2)"\n\tVisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.'

In [14]:
A.query(f':SENSe1:DATA?')

'-6.000000E-06,+1.984000E-09,+9.910000E+37,+4.112500E-02,+1.664000E+03,+0.000000E+00,+2.000010E-01,+1.989800E-08,+9.910000E+37,+2.595430E-01,+1.664000E+03,+1.000000E-01,+2.999970E-01,+2.974800E-08,+9.910000E+37,+4.592860E-01,+1.664000E+03,+2.000000E-01,+3.999940E-01,+3.859300E-08,+9.910000E+37,+6.786520E-01,+1.664000E+03,+3.000000E-01,+5.000050E-01,+4.832700E-08,+9.910000E+37,+8.709600E-01,+1.664000E+03,+4.000000E-01,+6.000010E-01,+5.850000E-08,+9.910000E+37,+1.110687E+00,+1.664000E+03,+5.000000E-01,+7.000010E-01,+6.229200E-08,+9.910000E+37,+1.296300E+00,+1.664000E+03,+6.000000E-01,+7.999950E-01,+7.832400E-08,+9.910000E+37,+1.498466E+00,+1.664000E+03,+7.000000E-01,+8.999970E-01,+9.253300E-08,+9.910000E+37,+1.701255E+00,+1.664000E+03,+8.000000E-01,+9.999980E-01,+1.055750E-07,+9.910000E+37,+1.903948E+00,+1.664000E+03,+9.000000E-01\n'

In [124]:
A.query('idle?')

'VISA ERROR:\n\tCommand: "idle?"\n\tVisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.'

In [126]:
A.write(f':SENSe1:DATA?') 

['VISA ERROR:\n\tCommand: ":SENSe1:DATA?"\n\tVisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.']

In [104]:
s1.get_sense_data(True)

'ERROR: A, channel 1:\n\tVISA ERROR:\n\tCommand: "sense1:data:latest?"\n\tVisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.'

In [105]:
s1.query('*OPC?')

'VISA ERROR:\n\tCommand: "*OPC?"\n\tVisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.'